import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Chain } from '@rainbow-me/rainbowkit'
import { SendTransaction } from '../component/sendTx'
import { SignMessage } from '../component/signMsg'
import { Contract } from '../component/contract'
import { Facuet } from '../component/facuet'
import { SignTypeData } from '../component/signTypeData'
import { SignTypeData2 } from '../component/signTypeData2'
import { WatchAsset } from '../component/watchAsset'
import { DecodeData } from '../component/decodedData'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flow Test App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Flow EVM Demo</h1>
        <ConnectButton showBalance={true} />
        <div className={styles.element}>
          <div className={styles.elementTitle}>Send FLOW Transaction</div>
          <SendTransaction />
        </div>
        <div className={styles.element}>
          <div className={styles.elementTitle}>Sign Message</div>
          <SignMessage />
        </div>
        <div className={styles.element}>
          <div className={styles.elementTitle}>Sign Typed Data</div>
          <SignTypeData />
          <SignTypeData2 />
        </div>
        <div className={styles.element}>
          <div className={styles.elementTitle}>Watch Assets</div>
          <WatchAsset />
        </div>
        <div>
          <div className={styles.elementTitle}>Decode Data</div>
          <DecodeData />
        </div>
        {/* <div className={styles.element}>
          <Contract/>
        </div> */}
        {/* <div className={styles.element}>
          <Facuet />
        </div> */}
      </main>
    </div>
  )
}

export default Home
