import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Chain } from '@rainbow-me/rainbowkit';
import { SendTransaction } from '../component/sendTx';
import { SignMessage } from '../component/signMsg';
import { Contract } from '../component/contract';
import { Facuet } from '../component/facuet'
import { SignTypeData } from '../component/signTypeData';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flow Test App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Flow EVM Demo
        </h1>
        <ConnectButton showBalance={true} />
        <SendTransaction/>
        <SignMessage/>
        <SignTypeData/>
        <Contract/>
        <Facuet />
      </main>
    </div>
  )
}

export default Home
